### ISSUE TITLE
No lines in SVG rendering

### ISSUE THREAD

**Issue by PanderMusubi** [GuntherRademacher/rr#17]
No lines in SVG rendering, reported for version 1.63. Lines are shown in PNG.

![Screenshot from 2022-05-15 19-59-32](https://user-images.githubusercontent.com/198964/168487181-77504a46-d315-4d03-bc51-d6f1771cb673.png)

**Comment by GuntherRademacher** [comment]
This happens when you save the XHTML+SVG output into a file with extension .html and let Chrome or Firefox render it. Even though the document contains an XHTML 1.0 Transitional Doctype declaration, browsers seen to rely on the file extension. It can be solved by using a file extension properly indicating XHTML, e.g. .xhtml.

**Comment by PanderMusubi** [comment]
Thanks, that fixed it indeed.
