### ISSUE TITLE
Bad parsing?

### ISSUE THREAD

**Issue by hmijail** [GuntherRademacher/rr#2]
This doesn't get well parsed, IIUC:
`Byte::= [ #x00 - #xFF ]` 

Should be a CharCode range. And each CharCode gets expanded to 4 digits.

**Comment by GuntherRademacher** [comment]
This looks like ignorable whitespace used in a CharClass definition, which it does not support: the relevant grammar rules are tagged [`/*ws: explicit*/`](https://www.w3.org/TR/2010/REC-xquery-20101214/#ExplicitWhitespaceHandling). What you want is
```
Byte::= [#x00-#xFF]
```

**Comment by hmijail** [comment]
Even then, the result ends up being [#x0000-#x00FF] instead of [#x00-#xFF], and overruns the box in the diagram.

**Comment by GuntherRademacher** [comment]
Admittedly adding the leading zeroes is somewhat arbitrary, so I will remove them somtime soon. But I can't see where it overruns the box. The SVG is rendered OK on the latest of Firefox, Chrome, and Opera, and the PNG looks OK as well.
![screenshot](https://user-images.githubusercontent.com/24464731/83230688-7cd34200-a18a-11ea-8c85-f1b16b1c21f1.png)
Could you please provide some more details of where and what you are observing?

**Comment by hmijail** [comment]
Firefox 77.0b9, macOS 10.15.3
![image](https://user-images.githubusercontent.com/4139546/83231449-db221400-a1ce-11ea-9106-817790639ad1.png)
But that is as it appears in the "view diagram" tab. The downloadable diagrams do look OK.

**Comment by GuntherRademacher** [comment]
Predending of leading zeroes has been removed in the source code, so these will vanish in the next release.

The [generated SVG](https://gist.github.com/GuntherRademacher/669e546633296cfb53d23438ed685edc?short_path=c0696cb) is always the same, it does not depend on the environment where it is rendered. But it may look slightly different on different browsers, even on the same OS, or on different versions of the same browser, because of differences in font handling. 

Usually the differences would be a few pixels only, but in this case it looks like a font of a larger size has been picked. Compared to usual sizes, the screenshot shows the box scaled up to 220%, but the font scale is 250-260%. 

However this seems to be a problem of this specific OS and browser combo. I do not own a Mac myself, but I have asked friends to check on several Macs and the effect did not reproduce anywhere. The closest was Firefox 76.0.1 on a 16" Macbook Pro running Mac OS 10.15.5, and it was fine there as well. 

There is nothing for me to do here.
