### ISSUE TITLE
Slight variation in production leads to "backwards" display

### ISSUE THREAD

**Issue by vsajip** [GuntherRademacher/rr#21]
The following production
```ebnf
key_value ::= ( key ( ':' | '=' ) value ( ',' | EOL )? EOL* )*
```
leads to diagram

![ss27](https://user-images.githubusercontent.com/130553/212379026-61cd9e2b-d367-46a3-89ae-0cdd29cf822e.png)

However, adding `EOL*` to the beginning of the production
```ebnf
key_value ::= EOL* ( key ( ':' | '=' ) value ( ',' | EOL )? EOL* )*
```
leads to

![ss28](https://user-images.githubusercontent.com/130553/212379978-b88a0577-94c9-47d5-98b2-033e07329b6b.png)

which, while not wrong, can confuse the reader because of the right-to-left ordering of `key` and `value` in the diagram. Is there a workaround for this? I tried changing some of the options but nothing caused left-to-right display of `key` and `value`.

**Comment by GuntherRademacher** [comment]
RR tries to detect repetitions with separators, and it comes up here with an empty repeated part, with everything else as the separator. This depends on the order of left- and right-factoring steps, and there is no way to influence this, but rephrasing the production. In this case you will get the desired result, if you put `EOL*` first in the original repetition, rather than last:
```ebnf
key_value ::= ( EOL* key ( ':' | '=' ) value ','? )* EOL* 
```
But what I would probably do is separate the key value pair from the repetion into separate productions:
```ebnf
key_value_pairs ::= EOL* ( key_value_pair EOL* )*
key_value_pair ::= key ( ':' | '=' ) value ','?
```
