### ISSUE TITLE
grammar Converter for offline use

### ISSUE THREAD

**Issue by amryounis** [GuntherRademacher/rr#27]
may I ask you to avail the grammar converter for download for offline work. thank you in advance

**Comment by GuntherRademacher** [comment]
Please find it [here](http://bottlecaps.de/convert/download/convert-0.65-java11.zip).

**Comment by mingodad** [comment]
Can we also get the source code ?

**Comment by GuntherRademacher** [comment]
> Can we also get the source code ?

Yes, when I am ready to provide it. Not at this time, sorry.

**Comment by mingodad** [comment]
Thank you for reply !
I'm also interested in the `REX` parser !
Cheers !

**Comment by GuntherRademacher** [comment]
[REx](https://bottlecaps.de/rex/) is not open source at this time, and there is no published documentation available either. Sorry.

**Comment by amryounis** [comment]
many thanks indeed

**Comment by alerque** [comment]
I landed here also looking for the converter. I've occasionally come round to use the online version, which was okay. Now the site is offline-for-me. Yes I know it is on IPv6, but my ISP isn't routing IPv6 at all and effectively it is offline for me. So I was looking for an offline version, but the tarball you linked is hosted also on the IPv6 only space, so I can't reach that either.

**Comment by mingodad** [comment]
Here https://github.com/GuntherRademacher/rr/releases/tag/v2.1 you can get it .

**Comment by alerque** [comment]
@mingodad That is unfortunately only the `rr` part, not the `convert` part.

**Comment by mingodad** [comment]
Can you mention what kind of grammar (yacc,antlr,...) are you trying to convert ?

**Comment by alerque** [comment]
In my case I have ABNF (RPC 5234 + RPC 7405) and I want other things such as what `rr` can render or that I can export to other tooling that doesn't handle ABNF (and perhaps does handle some flavor of EBNF or others).

**Comment by mingodad** [comment]
Maybe @GuntherRademacher  can make it available through github too ?
Let's see when he reply here !

**Comment by alerque** [comment]
I was able to get onto the https://www.bottlecaps.de site via Tor (which seems to be a great bridge to get around being stuck on an IPv4 only ISPs). I also have access to a server in Europe with proper IPv6 support and have tried command line downloads from there. Lastly I tried checking archive.org and their Internet Archive.

In all cases I struck out on getting the zip file with the `convert` binary linked above. I tried using the `www.` subdomain instead of the apex domain as well, but the file does not seem to be there at that link.

@GuntherRademacher It would be lovely if you could release that zip here on GitHub or indeed anywhere current. Of course as others have requested the source would be nice to see too, but even just the existing offline binary would be nice to be able to do local validation/conversion. I realize we're just out here asking for free stuff. I can only point to my FOSS contributions in many other areas including software you've surely used when I say: pretty please?

**Comment by GuntherRademacher** [comment]
@alerque Please note that only the latest version is avaible for downloading, that the link includes the version number, which has changed due to my domain name problem. The current link is [https://www.bottlecaps.de/convert/download/convert-0.66-java11.zip](https://www.bottlecaps.de/convert/download/convert-0.66-java11.zip). 

I will publish the source code on GitHub, I am just asking a little more time.  Thanks for using my code.

**Comment by alerque** [comment]
Thank you, that's fantastic! I can now run it locally instead of trying to fire off requests through Tor!

I see now the current running version is in the footer, but since the file isn't linked anywhere I didn't make that connection before.

Can I make a suggestion towards open sourcing this? I would give it a slightly more unique name so that it can be more easily packaged and integrated in other systems? For example perhaps `ebnf-convert` or `convert-to-ebnf` might work. The `convert` name is pretty definitively tied up by ImageMagick (also a bad choice of name and thankfully dropped in favor of `magick convert`, but lots of legacy code out there means it won't go away soon).

**Comment by alerque** [comment]
In fact if you have any naming ideas now even before you do a source release I'd like to put together an AUR recipe (-bin flavor) to make this easier to spin up in CI. I could do this now with a small shell wrapper script (which it needs to run `java -jar convert.war` anyway) but it would be nice to name it something you approved of and might make official later...

**Comment by alerque** [comment]
Wow, that's fantastic. I've successfully built it from source on Arch Linux and setup an AUR package so others can run it easily too.

I'm now looking at packaging `rr` too, and it looks like that name is already staked out by another project not only on Arch Linux but Debian, Ubuntu, Alt Linux, Apertis, Deepin, Duvuan, EPEL, Fedora, Gentoo, Guix, Kali, Nix, openSUSE, Pardus, Void, and many others [see repology](https://repology.org/project/rr-record-replay/versions).

I can rename it in packaging, but again if you would consider either renaming it here or at least suggesting a "sanctioned" alternative name like `ebnf-rr`, `ebnf-railroad` (both 100% clear) or perhaps just `railroad` (a bit sketchy because existing Python and Ruby project exist so package names might still be different with this name but /usr/bin/roalroad would probably be available)? That way any other distros trying to follow suite and documentation about how to run on different platforms could be consistent.
