### ISSUE TITLE
Consider project rename to avoid packaging confilcs

### ISSUE THREAD

**Issue by alerque** [GuntherRademacher/rr#29]
From #27 with is starting to wander off topic...

I'm now looking at packaging `rr` in adition to `ebnf-convert`, and it looks like the "rr" name is already staked out by another project not only on Arch Linux but Debian, Ubuntu, Alt Linux, Apertis, Deepin, Duvuan, EPEL, Fedora, Gentoo, Guix, Kali, Nix, openSUSE, Pardus, Void, and many others [see repology](https://repology.org/project/rr-record-replay/versions).

I can rename it in packaging, but again if you would consider either renaming it here or at least suggesting a "sanctioned" alternative name like `ebnf-rr`, `ebnf-railroad` (both 100% clear) or perhaps just `railroad` (a bit sketchy because existing Python and Ruby project exist so package names might still be different with this name but /usr/bin/roalroad would probably be available)? That way any other distros trying to follow suite and documentation about how to run on different platforms could be consistent.

**Comment by GuntherRademacher** [comment]
Thank you for your continued effort. In this case I would rather refrain from renaming the project, because it has been around for quite some time. If I were to package it, I'd name it `rr-webapp`. This name is aready used for the same on [Maven Central](https://central.sonatype.com/artifact/de.bottlecaps.rr/rr-webapp). It might neglect the fact that it also is a command line application, but that could be emphasized in the description.

**Comment by alerque** [comment]
Just a followup, unfortunately the "webapp" name doesn't play very nice with Arch package ecosystem as webapp packages are kind of thing and include some expectations about how config files and services are handled, and this has none of that. It isn't actually a webapp at all the way it is packaged (even if people are free to manually run it as one). As such I ended up packaging this under the name [`ebnf-rr`](https://aur.archlinux.org/packages/ebnf-rr) in the AUR.

**Comment by GuntherRademacher** [comment]
OK - thank you!
